project_id = "xephvqlmorubfvujxvck"

[functions.create-connect-account]
verify_jwt = true

[functions.create-marketplace-payment]
verify_jwt = true

[functions.check-connect-status]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.update-space-rating]
verify_jwt = false